apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
  namespace: staging
  labels:
    app: app-go
spec:
  selector:
    matchLabels:
      app: app-go
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  app-go
      labels:
        app: app-go
    spec:
      containers:
      - name: app-go
        image: marcellmartini/apps:sha-082bd4e
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: app-go
      restartPolicy: Always
