# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: app-go
  namespace: default
spec:
  selector:
    app: app-go
  type: ClusterIP
  ports:
  - name: app-go
    protocol: TCP
    port: 80
    targetPort: 8080

